print("          _________          ")
print("         /         \\         ")
print("        /  RUMAH    \\        ")
print("       /    ZIKRI    \\       ")
print("      /_______________\\      ")
print("      |    _____     |      ")
print("      |   |     |    |      ")
print("      |   |_____|    |      ")
print("      |     ___      |      ")
print("      |    |   |     |      ")
print("      |    |___|     |      ")
print("      |______________|      ")
print("      |  __      __  |      ")
print("      | |  |    |  | |      ")
print("      | |__|    |__| |      ")
print("      |____|  |______|     ")
print("                           ")
print("   #######################   ")
print("   ##  ##  ##  ##  ##  ##   ")
print("   ##  ##  ##  ##  ##  ##   ")
print("   ##  ##  ##  ##  ##  ##   ")
print("   #######################   ")
print("      IBARATNYA RUMBUT HIJAU ")
